### ISSUE TITLE
flake8

### ISSUE THREAD

**Issue by berk76** [underground-lab/eu2020#30]
* parametry `flake8` které jsou nyní v actions bych přesunul do `tox.ini` a v actions bych ho spuštěl bez parametrů
* v případě nálezu bych nechal action failnout

Co na to říkáš @mportesdev?

**Comment by mportesdev** [comment]
Klidně, uvidíme jak moc bude bez parametrů přísný.

Používáš tox u tohohle projektu? Já ho neumím, jen zhruba vím, na co se používá.

**Comment by berk76** [comment]
Používám jen soubor `tox.ini` pro parametrizování flake8, viz [dokumentace](https://flake8.pycqa.org/en/latest/user/configuration.html#configuration-locations)
